import type { NextPage } from "next";
import Head from "next/head";
import { CgMathEqual } from "react-icons/cg";

import { NavBar } from "../components/NavBar";

import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containercontent}>
        <div className={styles.containersvg}>
          <CgMathEqual />
        </div>
        <NavBar />
      </div>
    </div>
  );
};

export default Home;
